### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by akenn**

### CODE REVIEW

**Comment by thejameskyle** [comment]
Could you please provide sources for this information?

**Comment by akenn** [comment]
If you search for "terin substack" on Google, you get back 286 results. Which of my 286 sources should I cite?

screen shot 2015-01-23 at 2 35 53 pm

**Comment by thejameskyle** [comment]
:+1: :shipit:

**Comment by likethemammal** [comment]
This is awesome

**Pull request merged**
